services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=whowantstorunstandup'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
