spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  application:
    name: who-wants-to-run-standup
  datasource:
    url: jdbc:postgresql://localhost:5432/whowantstorunstandup
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
