spring:
  security:
    user:
      name: user
      password: password
  application:
    name: who-wants-to-run-standup
  datasource:
    url: jdbc:postgresql://localhost:5432/whowantstorunstandup
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update